### ISSUE TITLE
badgesConfig -> tooltip -> links, link not clickable

### ISSUE THREAD

**Issue by michagee** [geometricpanda/geometricpanda#31]
# 🐞 bug report

### Description

A config in preview.js with the tooltip attribute set containing an array of links:

```
badgesConfig: {
    section: {
      styles: {
        backgroundColor: '#FFF',
        borderColor: '#018786',
        color: '#018786',
      },
      title: 'Section',
      tooltip: {
        title: 'This component belongs in a "section"',
        desc: 'Components with the section flag should be put in a section.',
        links: [
          { title: 'Read more', href: `${window.location.origin}/?path=/story/items-section--default` },          
        ],
      },
    },
}
```
In the rendered output of the story, the link "Read more" is not clickable. Altough it is possible with "right-click" "open in new tab" to navigate to the link.

## 🌍  Your Environment

Storybook Version: 6.2
Browser: Google Chrome 93.0.4577.82
OS: Windows 10
@geometricpanda Version: latest

**Comment by jimdrury** [comment]
Hey,
i've had a look into this, i dont think that this is caused by this plugin.

If you add a debugger to `preventDefault` using the Chrome console:

```
const oldEPD = Event.prototype.preventDefault;
Event.prototype.preventDefault = function() {
    debugger;
    oldEPD.call(this);
};
```

When you click on the link, you can see that `preventDefault` is being called deep within the stack.

However, if you take a look at the [Storybook Links addon](https://storybook.js.org/addons/@storybook/addon-links) - that may be able to help you.
