### ISSUE TITLE
Create an own badge

### ISSUE THREAD

**Issue by shestakova1806** [geometricpanda/geometricpanda#37]
# 🚀 feature request

### Description
I want t have an opportunity to create my own badge with my custom name.

### Describe alternatives you've considered
For now I can define custom title for existing badge: `beta: { title: 'Rework' }`.
But in the stories I have to use the name from the package `badges: [BADGE.BETA]` and it's confusing.

**Comment by shestakova1806** [comment]
Found a way

**Comment by maximecote57** [comment]
@shestakova1806 How did you do it?

**Comment by MaiLeeTR** [comment]
@maximecote57 I was looking for same answer. I ended up redefining each key and adding custom ones (add styles in preview.js for customs) and importing from constants.js into my stories instead of `import { BADGE } from '@geometricpanda/storybook-addon-badges';` Hope that helps.

<img width="285" alt="Screen Shot 2022-06-12 at 4 53 44 AM" src="https://user-images.githubusercontent.com/55507048/173227696-503da484-015d-403e-a0b3-fca9db423c7a.png">

**Comment by jimdrury** [comment]
Hey, just to let you know, you can use any Enum, not just the one I provided.

You don’t need to keep the same values as I did too
